# Docs: https://github.com/yazi-rs/yazi-rs.github.io/blob/main/docs/configuration/keymap.md
# Default: https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml

[[mgr.prepend_keymap]]
on   = [ "g", "g" ]
run  = "plugin vcs-files"
desc = "Show Git file changes"

