# Docs: https://github.com/yazi-rs/yazi-rs.github.io/blob/main/docs/configuration/yazi.md
# Default: https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml

[mgr]
show_hidden = true

[preview]
wrap = "yes"

[[plugin.prepend_previewers]]
name = "*"
run = 'piper -- bat --color=always --number "$1"'

[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"

